### ISSUE TITLE
Organizer Metadata

### ISSUE THREAD

**Issue by sbddesign** [atlantabitdevs/bitdevs-upgrade#10]
We need to provide some customizability for organizers. Here's what I can think of at the moment:

- [x] Meetup Name (e.g. "NYC" or "Atlanta") #11 
- [x] City Position - first or last (e.g. BitDevs NYC has the meetup name in last position, Atlanta BitDevshas meetup name in first position) #12 
- [x] Color Palette - Need to define a primary and secondary hex code (this is low priority and we should evaluate how to do this appropriately with Tailwind compatibility) #13 

Consider how to do this in a scalable way. Ideally, people can customize their BitDevs site without needing to monkey with the theme files. So perhaps there is a `meetup.json` which stores metadata about the meetup and website?

**Comment by bnonni** [comment]
General Context / Requirements:
- Template should be scalable and maintainable
- Don't want organizers "monkeying around" with template files
- For updates / edits, they should use "organizer metadata" file to change various aspects of the site

**Comment by bnonni** [comment]
- created file `metaupdate.ts` where organizers add their meetup unique data
- implemented `interface Metaupdata` located in `types/Metaupdata.ts`
- created component `MeetupName.tsx`
